### ISSUE TITLE
Update to 4.3.1 (is this snap still being maintained?)

### ISSUE THREAD

**Issue by eeickmeyer** [snapcrafters/thelounge#21]
### What changes would you like?

Current version of TheLounge is 4.3.1. I see Stable and Beta branches of the snap are still on 4.2.0, while edge is still on 4.3.0. It seems as though the snap might not be maintained?

**Comment by lucyllewy** [comment]
It's maintained. I'm the maintainer ☺️ I just haven't had much time to focus on it lately. I'll try to have a look soon.

**Comment by eeickmeyer** [comment]
DANI!!! Good to read you! Thanks!
