### ISSUE TITLE
Fails store review

### ISSUE THREAD

**Issue by popey** [snapcrafters/thelounge#7]
`found potentially sensitive files in package: node_modules/tar/lib/.mkdir.js.swp lint-snap-v2_iffy_files`

Probably need to rm or prime it out.

**Comment by lucyllewy** [comment]
This should be fixed by PR #6

**Comment by lucyllewy** [comment]
Confirmed fixed. @popey can you close this issue please (I don't have the permission to do so :-() ... alternatively you could give me more powah :-p

**Comment by popey** [comment]
Will look at POWER options next week. ta! :D
